### ISSUE TITLE
Gazebo Stuck at Preparing World

### ISSUE THREAD

**Issue by adrianbadarau** [udacity/simple_arm_01#1]
I am new to ROS and Gazebo, but I am having trouble launching this project on the UDACITY provided VM.

Every time i launch Gazebo it gets stuck at "Preparing your world" step.

The VM has 8 GB of RAM assigned, 4 cores and 2GB of display memory, it have access to the internet with a download speed of ~100 MB/s

**Comment by sea-bass** [comment]
This happened to me too -- it just takes a while to download stuff from the Internet the first time. If you give it a couple of minutes, it should start up just fine.

**Comment by UAnjali** [comment]
We hope this issue is resolved and are closing out the issue.
